### ISSUE TITLE
[Feature Request] 优化md格式 Action

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/document#150]
### Describe the feature

https://github.com/creyD/prettier_action

### Additional context

```yaml
name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write **/*.{md}
          commit_message: "style: prettify code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
